### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Ziquiet** [Oknolaz/vasisualy#1]
~/tools/vasisualy >>> python3 vasisualy-qt.py                                  

Traceback (most recent call last):
  File "/home/ziquiet/tools/vasisualy/vasisualy-qt.py", line 15, in <module>
    from VasQt import map
  File "/home/ziquiet/tools/vasisualy/VasQt/map.py", line 30, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/lib/python3.9/site-packages/PyQt5/__init__.py)

**Comment by Oknolaz** [comment]
Что за дистрибутив?

**Comment by Oknolaz** [comment]
Закрыто по причине отсутствия ответа.

**Comment by Ziquiet** [comment]
Дистрибутив manjaro. Инструкция для установки на arch не помешала бы.

**Comment by vantu5z** [comment]
В процессе создания пакета для Arch. Осталось немного разобраться с зависимостями.

upd:
Добавил пакет в AUR https://aur.archlinux.org/packages/vasisualy-git/
Есть небольшая проблема с `pyowm`, которому нужен `python-geojson`, а он пока не поддерживает python 3.9
https://github.com/jazzband/geojson/pull/156
