### ISSUE TITLE
В Ubuntu 21.10 не работает

### ISSUE THREAD

**Issue by foxrus** [Oknolaz/vasisualy#12]
Привет, я установил в Ubuntu 21.10, ассистент запускается, но он меня не слышит, хотя по микрофону видно, что он работает.

<pre><font color="#26A269"><b>linuxcool@fox-pc</b></font>:<font color="#12488B"><b>~/vasisualy-pi</b></font>$ python3 run.py
Привет, меня зовут Васисуалий. Чем могу быть полезен?
[sys] ТИХО!..
[sys] Говорите...
[sys] Речь распознаётся...
[sys] Говорите...
[sys] Речь распознаётся...
[sys] Говорите...
[sys] Речь распознаётся...
[sys] Говорите...
[sys] Речь распознаётся...
</pre>

**Comment by Oknolaz** [comment]
В `Pi` версии нужно обращаться к ассистенту. Например: "_**Васисуалий**, расскажи новости_"
