### ISSUE TITLE
Плохое качество голоса.

### ISSUE THREAD

**Issue by xziy** [Oknolaz/vasisualy#2]
Я запустил асистента на Pi4 + paspbian, и сталкнулся с проблемой что голос воспроизводится с очень низким качеством
[пример.zip](https://github.com/Oknolaz/vasisualy/files/5806351/voice.zip)

**Comment by Oknolaz** [comment]
Вы должны установить синтезатор речи RHVoice:
sudo add-apt-repository ppa:linvinus/rhvoice
sudo apt-get update
sudo apt-get install speech-dispatcher-rhvoice rhvoice-russian
После этого голос должен измениться.

**Comment by coindroid42** [comment]
Я пробовал это но получал ошибку 

> aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

поэтому собрал из исходников, но это почемуто не работает так как задумано, я подозреваю что проблема в speech-dispatcher-rhvoice потомучто тест RHVoice работает нормально, звук голоса хорший.

**Comment by coindroid42** [comment]
Я починил, помогла эта статья http://linux.tiflocomp.ru/docs/spd_rhvoice_festival.php
конкретно я добавил модуль в дипатчер

> sudo cp -a /usr/local/bin/sd_rhvoice /usr/lib/speech-dispatcher-modules

**Comment by xziy** [comment]
Спасибо, Я пробовал это но получал ошибку 

> aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

поэтому собрал из исходников, но это почемуто не работает так как задумано, помог ваш ответ, я понял что проблема в speech-dispatcher-rhvoice потомучто тест RHVoice работает нормально, звук голоса хорший.

Позже я починил, помогла эта статья http://linux.tiflocomp.ru/docs/spd_rhvoice_festival.php
конкретно я добавил модуль в дипатчер

> sudo cp -a /usr/local/bin/sd_rhvoice /usr/lib/speech-dispatcher-modules
