### ISSUE TITLE
Вынести скилы в модули

### ISSUE THREAD

**Issue by coindroid42** [Oknolaz/vasisualy#4]
Хотелось бы иметь возможность кастомизировать скилы под свои нужды. Чтобы не форкать проект, да и может мои скилы совсем не нужны никому. Было бы хорошо если бы можно было добавить файлы в папку skils и "Васа"  их подхватил бы.

**Comment by Oknolaz** [comment]
Это отличная идея. Я попытаюсь её реализовать.

**Comment by Oknolaz** [comment]
Дело сделано, но только нет автоопределения скиллов, их придётся добавлять вручную.
