### ISSUE TITLE
Структура проекта и установка

### ISSUE THREAD

**Issue by vantu5z** [Oknolaz/vasisualy#9]
На данный момент предполагается установка программы в `/usr/share/vasisualy[-pi]` и к этому пути привязаны файлы запуска из [vasisualy-additional-files](https://github.com/Oknolaz/vasisualy-additional-files), что не совсем правильно.

Думаю стоит постараться сделать как в этом [руководстве](https://docs.python.org/3/install/).
Это сильно облегчит создание пакетов для дистрибутивов.

```
git-repository/
  - run.py                                      (для запуска и отладки исходников)
  - setup.py                                    (сборка пакета python)
  - лицензия и прочие файлы репозитория
  - vasisualy[-pi]/                             (каталог пакета)
    - __init__.py                               (файл инициализации, может быть пустым)
    - main.py
    - остальные каталоги и файлы пакета
```

Файлы `run.py` будут содержать нечто подобное:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from vasisualy import main
main()
```
Также будет необходимо немного изменить импорт модулей программы (на примере main.py):
либо сделать его относительным:
```
from .ui import design
```
либо с указанием пакета:
```
from vasisualy.ui import design
```

В части файла запуска `vasisualy.desktop`:
`Exec=/usr/bin/vasisualy` можно сократить до `Exec=vasisualy`
Если иконку положить в `/usr/usr/share/icons/hicolor/.../vasisualy.png`
`Icon=/usr/share/vasisualy/ui/vas.png` можно использовать `Icon=vasisualy`

**Comment by vantu5z** [comment]
Есть небольшая проблема с дополнительными данными (иконка, звуки). Похоже в `setup.py` нужно сделать вот так:
```
    package_data={
        'vasisualy': ['assets/shot.wav', 'assets/misfire.wav'],
        'vasisualy.ui': ['vas.png']
```
Кстати, а `music/test.wav` не нужен?

**Comment by Oknolaz** [comment]
Сам звуковой файл не нужен, он используется для тестирования навыка проигрывателя. Для работы нужна лишь папка music в директории проекта.
